from typing import List, Optional, Protocol
from domain.inventory import InventoryProduct


class ProductRepository(Protocol):
    def list_products(self, franchise_id: Optional[int], category: Optional[str] = None) -> List[InventoryProduct]: ...
    def get_product(self, product_id: int, franchise_id: Optional[int]) -> Optional[InventoryProduct]: ...
    def update_product(self, product_id: int, franchise_id: Optional[int], changes: dict) -> Optional[InventoryProduct]: ...


class InventoryServicePort(Protocol):
    def list_products(self, franchise_id: Optional[int], category: Optional[str] = None) -> List[InventoryProduct]: ...
    def get_product(self, product_id: int, franchise_id: Optional[int]) -> Optional[InventoryProduct]: ...
    def update_product(self, product_id: int, franchise_id: Optional[int], changes: dict) -> Optional[InventoryProduct]: ...
    def alerts(self, franchise_id: Optional[int]) -> List[InventoryProduct]: ...
